# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=gmake
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/rtmp_file_server
CFG_INC=-I../rtmp_server_base -I.. -Irtmp_file_server_cpp -I. 
CFG_LIB=../rtmp_server_base/librtmp/librtmp.a \
	../rtmp_server_base/polarssl-1.1.1/library/libpolarssl.a \
	../rtmp_server_base/zlib-1.2.5/libz.a -lpthread 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/aac_frame_reader.o $(OUTDIR)/amf_byte_stream.o \
	$(OUTDIR)/bit_reader.o $(OUTDIR)/bit_writter.o $(OUTDIR)/data_list.o \
	$(OUTDIR)/file_rtmp_server.o $(OUTDIR)/flv_reader.o \
	$(OUTDIR)/flv_writter.o $(OUTDIR)/h264_frame_parser.o \
	$(OUTDIR)/h264_frame_reader.o $(OUTDIR)/lib_rtmp.o $(OUTDIR)/main.o \
	$(OUTDIR)/rtmp_connection.o $(OUTDIR)/simple_mutex.o \
	$(OUTDIR)/thread.o $(OUTDIR)/util_tools.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/aac_frame_reader.o $(OUTDIR)/amf_byte_stream.o \
	$(OUTDIR)/bit_reader.o $(OUTDIR)/bit_writter.o $(OUTDIR)/data_list.o \
	$(OUTDIR)/file_rtmp_server.o $(OUTDIR)/flv_reader.o \
	$(OUTDIR)/flv_writter.o $(OUTDIR)/h264_frame_parser.o \
	$(OUTDIR)/h264_frame_reader.o $(OUTDIR)/lib_rtmp.o $(OUTDIR)/main.o \
	$(OUTDIR)/rtmp_connection.o $(OUTDIR)/simple_mutex.o \
	$(OUTDIR)/thread.o $(OUTDIR)/util_tools.o \
	../rtmp_server_base/librtmp/librtmp.a \
	../rtmp_server_base/polarssl-1.1.1/library/libpolarssl.a \
	../rtmp_server_base/zlib-1.2.5/libz.a -lpthread 

COMPILE=g++ -c    -g -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -g -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

$(OUTDIR)/%.o : ../rtmp_server_base/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : rtmp_file_server_cpp/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : %.c
	$(COMPILE)

$(OUTDIR)/%.o : ../rtmp_server_base/%.c
	$(COMPILE)

$(OUTDIR)/%.o : rtmp_file_server_cpp/%.c
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)
	----@echo -e "\e[1;31m all compiled  job finished! \e[0m"

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/rtmp_file_server
CFG_INC=-I../rtmp_server_base -I.. -Irtmp_file_server_cpp -I. 
CFG_LIB=../rtmp_server_base/librtmp/librtmp.a \
	../rtmp_server_base/polarssl-1.1.1/library/libpolarssl.a \
	../rtmp_server_base/zlib-1.2.5/libz.a -lpthread 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/aac_frame_reader.o $(OUTDIR)/amf_byte_stream.o \
	$(OUTDIR)/bit_reader.o $(OUTDIR)/bit_writter.o $(OUTDIR)/data_list.o \
	$(OUTDIR)/file_rtmp_server.o $(OUTDIR)/flv_reader.o \
	$(OUTDIR)/flv_writter.o $(OUTDIR)/h264_frame_parser.o \
	$(OUTDIR)/h264_frame_reader.o $(OUTDIR)/lib_rtmp.o $(OUTDIR)/main.o \
	$(OUTDIR)/rtmp_connection.o $(OUTDIR)/simple_mutex.o \
	$(OUTDIR)/thread.o $(OUTDIR)/util_tools.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/aac_frame_reader.o $(OUTDIR)/amf_byte_stream.o \
	$(OUTDIR)/bit_reader.o $(OUTDIR)/bit_writter.o $(OUTDIR)/data_list.o \
	$(OUTDIR)/file_rtmp_server.o $(OUTDIR)/flv_reader.o \
	$(OUTDIR)/flv_writter.o $(OUTDIR)/h264_frame_parser.o \
	$(OUTDIR)/h264_frame_reader.o $(OUTDIR)/lib_rtmp.o $(OUTDIR)/main.o \
	$(OUTDIR)/rtmp_connection.o $(OUTDIR)/simple_mutex.o \
	$(OUTDIR)/thread.o $(OUTDIR)/util_tools.o \
	../rtmp_server_base/librtmp/librtmp.a \
	../rtmp_server_base/polarssl-1.1.1/library/libpolarssl.a \
	../rtmp_server_base/zlib-1.2.5/libz.a -lpthread 

COMPILE=g++ -c   -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

$(OUTDIR)/%.o : ../rtmp_server_base/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : rtmp_file_server_cpp/%.cpp
	$(COMPILE)

$(OUTDIR)/%.o : %.c
	$(COMPILE)

$(OUTDIR)/%.o : ../rtmp_server_base/%.c
	$(COMPILE)

$(OUTDIR)/%.o : rtmp_file_server_cpp/%.c
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)
	----@echo -e "\e[1;31m all compiled  job finished! \e[0m"

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif
